const PATH = {
  API: 'api',
  V1: 'v1',
  CAKES: 'cakes',
  PAY: 'pay',
  AUTH: 'auth',
  WISHES: 'wishes',
  MAIN: 'main',
  APPROVE: 'approve',
  READY: 'ready',
  PG_TOKEN: 'pg_token',
  PRESENT: 'present',
  INFO: 'info',
  KAKAO: 'kakao',
  CALLBACK: 'callback',
  USER: 'user',
  ACCOUNT: 'account',
  PROGRESS: 'progress',
  FILE: 'file',
  FILE_NAME: 'fileName',
  PUBLIC: 'public',
  REDIRECT_URI: 'redirectUri',
};

export default PATH;
