import {
  BeefCakeImg,
  ChickenCakeImg,
  CoffeeCakeImg,
  PoopCakeImg,
  SushiCakeImg,
  FlowerCakeImg,
  PerfumeCakeImg,
  VitaminCakeImg,
  BeefCakeDetailImg,
  ChickenCakeDetailImg,
  CoffeeCakeDetailImg,
  PoopCakeDetailImg,
  SushiCakeDetailImg,
  FlowerCakeDetailImg,
  PerfumeCakeDetailImg,
  VitaminCakeDetailImg,
  BeefCakeThanksImg,
  ChickenCakeThanksImg,
  CoffeeCakeThanksImg,
  PoopCakeThanksImg,
  SushiCakeThanksImg,
  FlowerCakeThanksImg,
  PerfumeCakeThanksImg,
  VitaminCakeThanksImg,
  BeefCakeSmallImg,
  VitaminCakeSmallImg,
  ChickenCakeSmallImg,
  SushiCakeSmallImg,
  FlowerCakeSmallImg,
  PerfumeCakeSmallImg,
  PoopCakeSmallImg,
  CoffeeCakeSmallImg,
  RudolphCakeImg,
  RudolphCakeDetailImg,
  RudolphCakeThanksImg,
  RudolphCakeSmallImg,
} from '@/public/assets/images';
import { CakeListType } from '@/types/cakes/cakeListType';

export const CAKE_LIST: CakeListType[] = [
  {
    name: '달콤 커피 케이크',
    price: 4900,
    cakeImage: CoffeeCakeImg,
    detailImage: CoffeeCakeDetailImg,
    thanksImage: CoffeeCakeThanksImg,
    smallImage: CoffeeCakeSmallImg,
    cakeNumber: 2,
  },
  {
    name: '상큼 비타민 케이크',
    price: 9900,
    cakeImage: VitaminCakeImg,
    detailImage: VitaminCakeDetailImg,
    thanksImage: VitaminCakeThanksImg,
    smallImage: VitaminCakeSmallImg,
    cakeNumber: 3,
  },
  {
    name: '바사삭 치킨 케이크',
    price: 17900,
    cakeImage: ChickenCakeImg,
    detailImage: ChickenCakeDetailImg,
    thanksImage: ChickenCakeThanksImg,
    smallImage: ChickenCakeSmallImg,
    cakeNumber: 4,
  },
  {
    name: '장인 초밥 케이크',
    price: 25900,
    cakeImage: SushiCakeImg,
    detailImage: SushiCakeDetailImg,
    thanksImage: SushiCakeThanksImg,
    smallImage: SushiCakeSmallImg,
    cakeNumber: 5,
  },
  {
    name: '샤랄라 꽃 케이크',
    price: 38900,
    cakeImage: FlowerCakeImg,
    detailImage: FlowerCakeDetailImg,
    thanksImage: FlowerCakeThanksImg,
    smallImage: FlowerCakeSmallImg,
    cakeNumber: 6,
  },
  {
    name: '몸보신 한우 케이크',
    price: 46900,
    cakeImage: BeefCakeImg,
    detailImage: BeefCakeDetailImg,
    thanksImage: BeefCakeThanksImg,
    smallImage: BeefCakeSmallImg,
    cakeNumber: 7,
  },
  {
    name: '킁킁 향수 케이크',
    price: 55900,
    cakeImage: PerfumeCakeImg,
    detailImage: PerfumeCakeDetailImg,
    thanksImage: PerfumeCakeThanksImg,
    smallImage: PerfumeCakeSmallImg,
    cakeNumber: 8,
  },
  {
    name: '구리구리 똥 케이크',
    price: 0,
    cakeImage: PoopCakeImg,
    detailImage: PoopCakeDetailImg,
    thanksImage: PoopCakeThanksImg,
    smallImage: PoopCakeSmallImg,
    cakeNumber: 1,
  },
  // {
  //   name: '루돌프 사슴코 케이크',
  //   price: 0,
  //   cakeImage: RudolphCakeImg,
  //   detailImage: RudolphCakeDetailImg,
  //   thanksImage: RudolphCakeThanksImg,
  //   smallImage: RudolphCakeSmallImg,
  //   cakeNumber: 1,
  // },
];
